CREATE DOMAIN IF NOT EXISTS vector AS DOUBLE ARRAY;

CREATE TABLE IF NOT EXISTS event_embeddings (
  event_id BIGINT PRIMARY KEY,
  embedding vector NOT NULL,
  embedding_model VARCHAR(255) NOT NULL,
  source_text_hash VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_interest_embeddings (
  user_id BIGINT PRIMARY KEY,
  embedding vector NOT NULL,
  embedding_model VARCHAR(255) NOT NULL,
  source_text_hash VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS embedding_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type VARCHAR(30) NOT NULL,
  entity_id BIGINT NOT NULL,
  operation_type VARCHAR(20) NOT NULL,
  source_text CLOB NOT NULL,
  source_text_hash VARCHAR(64) NOT NULL,
  embedding_model VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_error_code VARCHAR(80),
  last_error_message VARCHAR(1000),
  request_id VARCHAR(128),
  processing_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_embedding_jobs_active_source
  ON embedding_jobs (entity_type, entity_id, embedding_model, source_text_hash, operation_type);
